### ISSUE TITLE
Small style edits

### ISSUE THREAD

**Issue by datalorax** [datalorax/sds-r#15]
- [x] Add GitHub icon to navbar that links back here
- [x] Add a default fill color. Could be any of the colors that look good in the `--highligh-*` vars in the CSS
- [x] @brendanhcullen tries to add sidenotes

The first two are simple, the third seems much more difficult. But, I also wanted to mention that if you're able to get this to work we should move the page navigation to be at the bottom always. Right now, page navigation is on the sides of the text if the window is wide enough, and at the bottom otherwise. If we can build in side-notes, we should probably just have it at the bottom always.

**Comment by brendanhcullen** [comment]
re: tufte-style margin notes, I've been playing around with this a bit, and so far haven't been super successful getting them to look good with the standard bookdown format. I'm gonna keep playing around with this, but just adding a few notes here for posterity:

Someone posted about this in RStudio Community a while back: https://community.rstudio.com/t/bookdown-contest-submission-gitbook-style-tufte-style-for-web-book/11666

Here's an example of what this hybrid approach looks like with their book: 
https://crumplab.github.io/programmingforpsych/fundamentals-of-computer-programming-languages.html#why-should-psychologists-learn-to-program

I think it forces some of the text to be too small, especially the table of contents on the left. I think that's why the tufte bookdown style puts the TOC on the top margin: https://bookdown.org/yihui/bookdown-demo3/2-intro.html#intro

**Comment by datalorax** [comment]
Thanks! That's really helpful. If we can't get it to work, it's not a big deal. I think things are generally looking pretty good. Side notes would just be an added bonus.
