### ISSUE TITLE
Review FE chapter

### ISSUE THREAD

**Issue by datalorax** [datalorax/sds-r#22]
It would be great if one or both of you could review the FE chapter. Basically, I think just look at the rendered version and look at the R Markdown and make any edits you think are needed. If there's something you think is not clear that needs further revision from me, feel free to add in a comment in the document.

In terms of workflow, I think just create a branch and go for it, then submit a PR with your review. There may be better ways, but that should generally work okay. If you have ideas on better workflow, I'm fully open to them.

**Comment by brendanhcullen** [comment]
@datalorax Gonna do this review now! Meant to do this a lot sooner, sorry. I'll go with the new PR approach for now. In terms of workflow going forward (especially as we start adding more chapters), it might keep things cleaner if we have one branch & one PR for each chapter and then whoever is reviewing the chapter can add their edits with a new commit to that same PR and add any necessary comments directly in Github? I think commenting in Github is cleaner because then you can create threads, keep track of who's saying what, and mark them as resolved, etc. That way we won't have to add/remove comments from the `.Rmd` files themselves. What do you think? We can also think about using the [Github projects](https://github.com/features/project-management/) feature, but that might be overkill for our purposes

**Comment by datalorax** [comment]
I like that idea generally, and think it's a great approach for the intro chapters. My only hesitation is that I'd really like to get the chapters I'm working on out ASAP, even if they're rough, so that the students have that resource (in addition to the slides and other reading).

So I think we should do what you suggest for the intro chapters, but just go forward with an additional PR for the chapters I'm writing because they're more time sensitive. Does that work?

**Comment by brendanhcullen** [comment]
oh right! yes that totally works. definitely want to prioritize making it available to students, so we can try out this workflow with section 1 content for now.
