### ISSUE TITLE
Git Chapter review

### ISSUE THREAD

**Issue by datalorax** [datalorax/sds-r#43]

**Comment by datalorax** [comment]
Just an FYI @ohmaddi this is ready to go. There's an open PR you can add edits to if you'd like (I'm okay waiting to merge since the term hasn't started) and the preview is [here](https://5fe26a818a92a91ce1ef5c5f--nervous-golick-ef3308.netlify.app/collaborating-with-git-and-github.html).

Whenever you get around to this is fine - no pressure at all. But if you think you won't be able to get to it before the term starts then I'll probably just merge it in and we can do the edits later.

**Comment by ohmaddi** [comment]
@datalorax I just completed the chapter review. It is really good and super helpful. I only made some minor text edits and one html comment regarding the repo initial files (gitignore and MIT license). 

Now that I read the chapter and finally understand the branching process much better (thank you), I realized I should have created a new branch for the review itself instead of making changes directly to your branch. But as I said the changes were minor. The next review should go smoothly with no mistakes. 

All the changes were pushed to the remote. You only need to look at the comment and then you can go ahead and merge.

**Comment by datalorax** [comment]
Thanks @ohmaddi! I'm fine with you pushing directly to this branch. I'll take a look and get it merged in later today!
